name: test
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup JDK11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64
    - name: Build and Test
      run: sbt -v +test
      env:
          GITHUB_TOKEN: ${{ secrets.SECRET_PACK }}


